name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your dependencies

    - name: Run tests
      run: |
        python manage.py test  # Run your Django tests

    - name: Deploy to server (if applicable)
      run: |
        ssh user@your-server-ip "cd /path/to/your/app && git pull && docker-compose up -d"  # Example deployment command
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}  # Reference the secret for SSH key
